# Generated by Django 4.2.7 on 2025-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_diagnosticoresultado_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoresultado',
            name='analise_ia',
            field=models.TextField(blank=True, help_text='Análise estratégica gerada via IA', null=True),
        ),
    ]
