# Generated by Django 4.2.7 on 2025-12-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_diagnosticoresultado_analise_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('recursos', models.JSONField(default=list, help_text='Lista de recursos inclusos')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['preco_mensal'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='cortesia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='cupom_desconto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CARTAO_RECORRENTE', 'Cartão de crédito recorrente'), ('BOLETO', 'Boleto bancário')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='indicador_comissao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='suporte_regiao',
            field=models.CharField(blank=True, choices=[('MATRIZ', 'Matriz'), ('PERNAMBUCO', 'Pernambuco'), ('CEARA', 'Ceará')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.plano'),
        ),
    ]
