# Generated by Django 4.2.7 on 2025-12-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_plano_oportunidade_cortesia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(default='unidade', help_text='Ex: usuário, CNPJ, hora', max_length=50)),
            ],
            options={
                'verbose_name': 'Adicional de Plano',
                'verbose_name_plural': 'Adicionais de Plano',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='periodo_pagamento',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OportunidadeAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.planoadicional')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Adicional da Oportunidade',
                'verbose_name_plural': 'Adicionais da Oportunidade',
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='adicionais',
            field=models.ManyToManyField(blank=True, through='crm.OportunidadeAdicional', to='crm.planoadicional'),
        ),
    ]
