# Generated by Django 4.2.7 on 2025-12-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_planoadicional_oportunidade_periodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('PADRAO', 'Padrão'), ('INDICADOR', 'Indicador de Comissão')], default='PADRAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='indicador_comissao',
            field=models.ForeignKey(blank=True, help_text='Contato que indicou esta oportunidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes', to='crm.contato'),
        ),
    ]
