# Generated by Django 4.2.7 on 2025-12-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contato_tipo_alter_oportunidade_indicador_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suporte_regiao',
            field=models.CharField(blank=True, choices=[('MATRIZ', 'Matriz'), ('PERNAMBUCO', 'Pernambuco'), ('CEARA', 'Ceará')], help_text='Região de suporte padrão para este usuário', max_length=50, null=True),
        ),
    ]
