# Generated by Django 4.2.7 on 2025-12-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_user_suporte_regiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='suporte_regiao',
            field=models.CharField(blank=True, choices=[('MATRIZ', 'Matriz'), ('PERNAMBUCO', 'Pernambuco'), ('CEARA', 'Ceará')], help_text='LEGACY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='suporte_regiao',
            field=models.CharField(blank=True, choices=[('MATRIZ', 'Matriz'), ('PERNAMBUCO', 'Pernambuco'), ('CEARA', 'Ceará')], help_text='Região de suporte padrão para este usuário (LEGACY)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.regiao'),
        ),
        migrations.AddField(
            model_name='user',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='crm.regiao'),
        ),
    ]
