# Generated by Django 4.2.7 on 2025-12-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_regiao_alter_oportunidade_suporte_regiao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='suporte_regiao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suporte_regiao',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='canal',
            field=models.ForeignKey(blank=True, help_text='Canal responsável pelo suporte/faturamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.canal'),
        ),
        migrations.DeleteModel(
            name='Regiao',
        ),
    ]
