# Generated by Django 4.2.7 on 2025-12-29 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_oportunidade_regiao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('LEAD', 'Leads (SDR)'), ('OPORTUNIDADE', 'Oportunidades (Vendas)')], default='OPORTUNIDADE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funil',
                'verbose_name_plural': 'Funis',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='estagiofunil',
            options={'ordering': ['funil', 'ordem'], 'verbose_name': 'Estágio do Funil', 'verbose_name_plural': 'Estágios do Funil'},
        ),
        migrations.AddField(
            model_name='estagiofunil',
            name='is_padrao',
            field=models.BooleanField(default=False, help_text='Define se este é o estágio inicial padrão para novos registros no funil'),
        ),
        migrations.AddField(
            model_name='lead',
            name='estagio',
            field=models.ForeignKey(blank=True, help_text='Estágio atual do lead no funil SDR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.estagiofunil'),
        ),
        migrations.AddField(
            model_name='funil',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuários que podem ver e usar este funil', related_name='funis_acesso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estagiofunil',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estagiofunil',
            name='funil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='crm.funil'),
        ),
        migrations.AddField(
            model_name='lead',
            name='funil',
            field=models.ForeignKey(blank=True, help_text='Funil SDR onde este lead está', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.funil'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='funil',
            field=models.ForeignKey(blank=True, help_text='Funil de vendas onde esta oportunidade está', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.funil'),
        ),
        migrations.AlterUniqueTogether(
            name='estagiofunil',
            unique_together={('funil', 'nome')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['funil', 'estagio'], name='crm_lead_funil_i_c0f261_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['funil', 'estagio'], name='crm_oportun_funil_i_ee1205_idx'),
        ),
    ]
