# Generated by Django 4.2.7 on 2025-12-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_funil_alter_estagiofunil_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contato',
                'verbose_name_plural': 'Tipos de Contatos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='contato',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='crm.canal'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(default='PADRAO', max_length=20),
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='crm.tipocontato'),
        ),
    ]
