# Generated by Django 4.2.7 on 2025-12-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_tipocontato_contato_canal_alter_contato_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estagiofunil',
            options={'ordering': ['nome'], 'verbose_name': 'Definição de Estágio', 'verbose_name_plural': 'Definições de Estágios'},
        ),
        migrations.AlterUniqueTogether(
            name='estagiofunil',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estagiofunil',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='FunilEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('is_padrao', models.BooleanField(default=False, help_text='Define se este é o estágio inicial padrão neste funil')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.estagiofunil')),
                ('funil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.funil')),
            ],
            options={
                'verbose_name': 'Estágio do Funil',
                'verbose_name_plural': 'Estágios dos Funis',
                'ordering': ['ordem'],
                'unique_together': {('funil', 'estagio')},
            },
        ),
        migrations.RemoveField(
            model_name='estagiofunil',
            name='funil',
        ),
        migrations.RemoveField(
            model_name='estagiofunil',
            name='is_padrao',
        ),
        migrations.RemoveField(
            model_name='estagiofunil',
            name='ordem',
        ),
        migrations.AddField(
            model_name='funil',
            name='estagios',
            field=models.ManyToManyField(related_name='funis_vinculados', through='crm.FunilEstagio', to='crm.estagiofunil'),
        ),
    ]
