# Generated by Django 4.2.7 on 2026-01-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_estagiofunil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='canal',
            field=models.ForeignKey(blank=True, help_text='Canal ao qual este lead pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.canal'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['canal', 'status'], name='crm_lead_canal_i_467930_idx'),
        ),
    ]
