# Generated by Django 4.2.7 on 2026-01-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_canal_lead_crm_lead_canal_i_467930_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas', to='crm.canal'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['canal'], name='crm_conta_canal_i_222c56_idx'),
        ),
    ]
