# Generated by Django 4.2.7 on 2026-01-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_conta_canal_conta_crm_conta_canal_i_222c56_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mensagem', models.CharField(help_text='ID da mensagem na Evolution API', max_length=255, unique=True)),
                ('instancia', models.CharField(max_length=100)),
                ('de_mim', models.BooleanField(default=False, help_text='True se enviada pelo CRM, False se recebida')),
                ('numero_remetente', models.CharField(max_length=50)),
                ('numero_destinatario', models.CharField(max_length=50)),
                ('texto', models.TextField(blank=True, null=True)),
                ('tipo_mensagem', models.CharField(default='text', help_text='text, image, video, document, etc', max_length=50)),
                ('url_media', models.URLField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='crm.lead')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['numero_remetente'], name='crm_whatsap_numero__e71b6c_idx'), models.Index(fields=['numero_destinatario'], name='crm_whatsap_numero__e3eb81_idx'), models.Index(fields=['timestamp'], name='crm_whatsap_timesta_a719c2_idx')],
            },
        ),
    ]
