# Generated by Django 4.2.7 on 2026-01-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='lida',
            field=models.BooleanField(default=False, help_text='True se a mensagem já foi visualizada no CRM'),
        ),
    ]
