# Generated by Django 4.2.7 on 2026-01-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_whatsappmessage_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_base64',
            field=models.TextField(blank=True, help_text='Base64 da mídia para exibição direta', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='tipo_mensagem',
            field=models.CharField(default='text', help_text='text, image, video, document, audio, etc', max_length=50),
        ),
    ]
