# Generated by Django 4.2.7 on 2026-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_add_media_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
