# Generated by Django 4.2.7 on 2026-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_contato_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='avatars/'),
        ),
    ]
