# Generated by Django 4.2.7 on 2026-01-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_add_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL do perfil no Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='instagram',
            field=models.CharField(blank=True, help_text='Nome de usuário no Instagram (sem @)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL do perfil no LinkedIn', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='twitter',
            field=models.CharField(blank=True, help_text='Nome de usuário no Twitter/X (sem @)', max_length=100, null=True),
        ),
    ]
