# Generated by Django 4.2.7 on 2026-01-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_add_contato_redes_sociais'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone ou classe CSS', max_length=50, null=True)),
                ('cor', models.CharField(default='#6B7280', help_text='Cor em hexadecimal', max_length=7)),
                ('url_base', models.CharField(blank=True, help_text='URL base para montar o link (ex: https://linkedin.com/in/)', max_length=255, null=True)),
                ('placeholder', models.CharField(blank=True, help_text='Texto de exemplo no campo', max_length=100, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Rede Social',
                'verbose_name_plural': 'Tipos de Redes Sociais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='contato',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='twitter',
        ),
        migrations.CreateModel(
            name='ContatoRedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Username ou URL do perfil', max_length=255)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='crm.contato')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='crm.tiporedesocial')),
            ],
            options={
                'verbose_name': 'Rede Social do Contato',
                'verbose_name_plural': 'Redes Sociais do Contato',
                'ordering': ['tipo__ordem'],
                'unique_together': {('contato', 'tipo')},
            },
        ),
    ]
