# Generated by Django 4.2.7 on 2026-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_popular_tipos_redes_sociais'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do contato', null=True, upload_to='contatos/'),
        ),
    ]
