# Generated by Django 4.2.7 on 2026-01-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_add_contato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontato',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji para exibir no dashboard (ex: 👤 📞 💼)', max_length=10, null=True),
        ),
    ]
