# Generated by Django 4.2.7 on 2026-01-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_add_tipocontato_emoji'),
    ]

    operations = [
    ]
