# Generated by Django 4.2.7 on 2026-01-06 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_add_audit_fields_to_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuário que atualizou o contato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contato',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o contato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
