# Generated by Django 4.2.7 on 2026-01-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_contato_atualizado_por_contato_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação')], max_length=20)),
                ('modelo', models.CharField(help_text='Nome do modelo afetado (ex: Contato, Lead, Oportunidade)', max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, help_text='ID do objeto afetado', null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representação em string do objeto', max_length=255, null=True)),
                ('alteracoes', models.JSONField(blank=True, help_text='JSON com as alterações realizadas. Ex: {"campo": {"antes": "valor1", "depois": "valor2"}}', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador', null=True)),
                ('observacao', models.TextField(blank=True, help_text='Observações ou contexto adicional', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que executou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='crm_log_usuario_66b22d_idx'), models.Index(fields=['modelo', 'objeto_id'], name='crm_log_modelo_bfb605_idx'), models.Index(fields=['acao', 'timestamp'], name='crm_log_acao_c6dee8_idx')],
            },
        ),
    ]
