# Generated by Django 4.2.7 on 2026-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='whatsapp_connected',
            field=models.BooleanField(default=False, help_text='Status da conexão WhatsApp'),
        ),
        migrations.AddField(
            model_name='canal',
            name='whatsapp_instance_id',
            field=models.CharField(blank=True, help_text='ID da instância Evolution API para este canal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número conectado ao WhatsApp', max_length=20, null=True),
        ),
    ]
