# Generated by Django 4.2.7 on 2026-01-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_whatsapp_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, help_text='API Key da instância Evolution para este canal', max_length=255, null=True),
        ),
    ]
