# Generated by Django 4.2.7 on 2026-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_whatsapp_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canal',
            old_name='whatsapp_connected',
            new_name='evolution_is_connected',
        ),
        migrations.RenameField(
            model_name='canal',
            old_name='whatsapp_number',
            new_name='evolution_phone_number',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='whatsapp_api_key',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='whatsapp_instance_id',
        ),
        migrations.AddField(
            model_name='canal',
            name='evolution_instance_name',
            field=models.CharField(blank=True, help_text='Nome da instância na Evolution API (ex: canal_brasilia)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='evolution_last_status',
            field=models.CharField(blank=True, help_text='Último status retornado (open, close, connecting, etc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='evolution_token',
            field=models.CharField(blank=True, help_text='Token/API Key da instância retornado pela Evolution', max_length=255, null=True),
        ),
    ]
