# Generated by Django 4.2.7 on 2026-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_evolution_fields_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='fonte',
            field=models.CharField(blank=True, help_text='Origem da oportunidade (Site, Evento, Indicação, etc)', max_length=100, null=True),
        ),
    ]
