# Generated by Django 4.2.7 on 2026-01-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_add_fonte_to_oportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='oportunidade_convertida',
            field=models.ForeignKey(blank=True, help_text='Oportunidade gerada a partir deste lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origem', to='crm.oportunidade'),
        ),
    ]
