# Generated by Django 4.2.7 on 2026-01-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_add_oportunidade_convertida_to_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('LEAD', 'Lead'), ('OPORTUNIDADE', 'Oportunidade')], max_length=20)),
                ('nome_estagio_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_estagio_novo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('estagio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_saidas', to='crm.funilestagio')),
                ('estagio_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_entradas', to='crm.funilestagio')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_estagios', to='crm.lead')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_estagios', to='crm.oportunidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_estagio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Estágio',
                'verbose_name_plural': 'Históricos de Estágios',
                'ordering': ['-data_mudanca'],
                'indexes': [models.Index(fields=['lead', 'data_mudanca'], name='crm_histori_lead_id_5c255d_idx'), models.Index(fields=['oportunidade', 'data_mudanca'], name='crm_histori_oportun_b7e8f5_idx'), models.Index(fields=['tipo_objeto', 'data_mudanca'], name='crm_histori_tipo_ob_5e763d_idx')],
            },
        ),
    ]
