# Generated by Django 4.2.7 on 2026-01-13 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_historico_estagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor', models.CharField(default='#6C5CE7', help_text='Cor em hexadecimal', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('CELULAR', 'Celular'), ('COMERCIAL', 'Comercial'), ('RESIDENCIAL', 'Residencial'), ('WHATSAPP', 'WhatsApp'), ('OUTRO', 'Outro')], default='CELULAR', max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='crm.contato')),
            ],
            options={
                'verbose_name': 'Telefone do Contato',
                'verbose_name_plural': 'Telefones dos Contatos',
                'ordering': ['-principal', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ContatoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('COMERCIAL', 'Comercial'), ('OUTRO', 'Outro')], default='COMERCIAL', max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.contato')),
            ],
            options={
                'verbose_name': 'Email do Contato',
                'verbose_name_plural': 'Emails dos Contatos',
                'ordering': ['-principal', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ContatoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contatos/anexos/')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crm.contato')),
                ('uploaded_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo do Contato',
                'verbose_name_plural': 'Anexos dos Contatos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.AddField(
            model_name='contato',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contatos', to='crm.tag'),
        ),
    ]
