# Generated by Django 4.2.7 on 2026-01-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_contato_multiplos_telefones_emails_tags_anexos'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoresultado',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='crm.oportunidade'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='contatos',
            field=models.ManyToManyField(blank=True, help_text='Contatos vinculados a esta oportunidade', related_name='oportunidades', to='crm.contato'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas vinculadas a esta oportunidade', related_name='oportunidades', to='crm.conta'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_legado', to='crm.conta'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='contato_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_principais', to='crm.contato'),
        ),
        migrations.CreateModel(
            name='OportunidadeAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='oportunidades/anexos/')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crm.oportunidade')),
                ('uploaded_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo da Oportunidade',
                'verbose_name_plural': 'Anexos da Oportunidade',
                'ordering': ['-data_upload'],
            },
        ),
    ]
