# Generated by Django 4.2.7 on 2026-01-13 14:46

from django.db import migrations, models
import django.db.models.deletion


def migrar_leads_para_oportunidades(apps, schema_editor):
    Lead = apps.get_model('crm', 'Lead')
    Oportunidade = apps.get_model('crm', 'Oportunidade')
    Contato = apps.get_model('crm', 'Contato')
    Conta = apps.get_model('crm', 'Conta')
    Funil = apps.get_model('crm', 'Funil')
    EstagioFunil = apps.get_model('crm', 'EstagioFunil')
    FunilEstagio = apps.get_model('crm', 'FunilEstagio')
    DiagnosticoResultado = apps.get_model('crm', 'DiagnosticoResultado')
    WhatsappMessage = apps.get_model('crm', 'WhatsappMessage')
    Atividade = apps.get_model('crm', 'Atividade')
    HistoricoEstagio = apps.get_model('crm', 'HistoricoEstagio')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # 1. Atualizar tipos de Funil
    Funil.objects.filter(tipo='LEAD').update(tipo='OPORTUNIDADE')

    # 2. Migrar cada Lead
    for lead in Lead.objects.all():
        # Criar ou buscar Conta
        conta = None
        if lead.empresa:
            conta = Conta.objects.filter(nome_empresa__iexact=lead.empresa).first()
            if not conta:
                conta = Conta.objects.create(
                    nome_empresa=lead.empresa,
                    proprietario=lead.proprietario,
                    canal=lead.canal
                )
        
        # Criar Contato
        contato = Contato.objects.create(
            nome=lead.nome,
            email=lead.email,
            telefone=lead.telefone,
            cargo=lead.cargo,
            conta=conta,
            proprietario=lead.proprietario,
            canal=lead.canal
        )
        
        # Criar Oportunidade
        opp = Oportunidade.objects.create(
            nome=f"Oportunidade - {lead.nome}",
            conta=conta,
            contato_principal=contato,
            proprietario=lead.proprietario,
            canal=lead.canal,
            funil=lead.funil,
            estagio=lead.estagio,
            fonte=lead.fonte or 'Lead Migrado',
            descricao=lead.notas,
            data_criacao=lead.data_criacao
        )
        # Seta a data de criação retroativa via update para burlar o auto_now_add
        Oportunidade.objects.filter(id=opp.id).update(data_criacao=lead.data_criacao)
        
        # Vincular contato e empresa à oportunidade (M2M)
        opp.contatos.add(contato)
        if conta:
            opp.empresas.add(conta)
        
        # 3. Re-vincular itens relacionados
        # Diagnósticos
        DiagnosticoResultado.objects.filter(lead=lead).update(
            lead=None,
            conta=conta,
            oportunidade=opp
        )
        
        # Mensagens WhatsApp
        WhatsappMessage.objects.filter(lead=lead).update(
            lead=None,
            oportunidade=opp
        )
        
        # Histórico de Estágios
        HistoricoEstagio.objects.filter(lead=lead).update(
            lead=None,
            oportunidade=opp,
            tipo_objeto='OPORTUNIDADE'
        )
        
        # Atividades (Polimórficas)
        lead_ct = ContentType.objects.get_for_model(Lead)
        opp_ct = ContentType.objects.get_for_model(Oportunidade)
        Atividade.objects.filter(content_type=lead_ct, object_id=lead.id).update(
            content_type=opp_ct,
            object_id=opp.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_diagnosticoresultado_oportunidade_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_leads_para_oportunidades),
        migrations.RemoveField(
            model_name='lead',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='estagio',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='funil',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='oportunidade_convertida',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='proprietario',
        ),
        migrations.RemoveIndex(
            model_name='historicoestagio',
            name='crm_histori_lead_id_5c255d_idx',
        ),
        migrations.RemoveField(
            model_name='diagnosticoresultado',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='historicoestagio',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='lead',
        ),
        migrations.AlterField(
            model_name='funil',
            name='tipo',
            field=models.CharField(choices=[('OPORTUNIDADE', 'Oportunidades')], default='OPORTUNIDADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicoestagio',
            name='tipo_objeto',
            field=models.CharField(choices=[('OPORTUNIDADE', 'Oportunidade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='modelo',
            field=models.CharField(help_text='Nome do modelo afetado (ex: Contato, Conta, Oportunidade)', max_length=100),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_diretas', to='crm.conta'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='contato_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_principais_contato', to='crm.contato'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
