# Generated by Django 4.2.7 on 2026-01-13 14:46
# PARTE 2: Alterações de schema (RemoveField, AlterField, DeleteModel)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_origem_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='estagio',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='funil',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='oportunidade_convertida',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='proprietario',
        ),
        migrations.RemoveIndex(
            model_name='historicoestagio',
            name='crm_histori_lead_id_5c255d_idx',
        ),
        migrations.RemoveField(
            model_name='diagnosticoresultado',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='historicoestagio',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='lead',
        ),
        migrations.AlterField(
            model_name='funil',
            name='tipo',
            field=models.CharField(choices=[('OPORTUNIDADE', 'Oportunidades')], default='OPORTUNIDADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicoestagio',
            name='tipo_objeto',
            field=models.CharField(choices=[('OPORTUNIDADE', 'Oportunidade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='modelo',
            field=models.CharField(help_text='Nome do modelo afetado (ex: Contato, Conta, Oportunidade)', max_length=100),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_diretas', to='crm.conta'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='contato_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_principais_contato', to='crm.contato'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
