# Generated by Django 4.2.7 on 2026-01-13 14:46
# PARTE 1: Apenas migração de dados (RunPython)

from django.db import migrations


def migrar_leads_para_oportunidades(apps, schema_editor):
    Lead = apps.get_model('crm', 'Lead')
    Oportunidade = apps.get_model('crm', 'Oportunidade')
    Contato = apps.get_model('crm', 'Contato')
    Conta = apps.get_model('crm', 'Conta')
    Funil = apps.get_model('crm', 'Funil')
    EstagioFunil = apps.get_model('crm', 'EstagioFunil')
    FunilEstagio = apps.get_model('crm', 'FunilEstagio')
    DiagnosticoResultado = apps.get_model('crm', 'DiagnosticoResultado')
    WhatsappMessage = apps.get_model('crm', 'WhatsappMessage')
    Atividade = apps.get_model('crm', 'Atividade')
    HistoricoEstagio = apps.get_model('crm', 'HistoricoEstagio')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # 1. Atualizar tipos de Funil
    Funil.objects.filter(tipo='LEAD').update(tipo='OPORTUNIDADE')
    
    # 2. Obter ou criar um estágio padrão para Leads sem estágio
    estagio_padrao = EstagioFunil.objects.first()
    if not estagio_padrao:
        estagio_padrao = EstagioFunil.objects.create(
            nome='Novo',
            tipo='ABERTO',
            cor='#3B82F6'
        )

    # 3. Migrar cada Lead
    for lead in Lead.objects.all():
        # Criar ou buscar Conta
        conta = None
        if lead.empresa:
            conta = Conta.objects.filter(nome_empresa__iexact=lead.empresa).first()
            if not conta:
                conta = Conta.objects.create(
                    nome_empresa=lead.empresa,
                    proprietario=lead.proprietario,
                    canal=lead.canal
                )
        
        # Criar Contato
        contato = Contato.objects.create(
            nome=lead.nome,
            email=lead.email,
            telefone=lead.telefone,
            cargo=lead.cargo,
            conta=conta,
            proprietario=lead.proprietario,
            canal=lead.canal
        )
        
        # Usar estágio do lead ou o padrão se não existir
        estagio_lead = lead.estagio if lead.estagio else estagio_padrao
        
        # Criar Oportunidade
        opp = Oportunidade.objects.create(
            nome=f"Oportunidade - {lead.nome}",
            conta=conta,
            contato_principal=contato,
            proprietario=lead.proprietario,
            canal=lead.canal,
            funil=lead.funil,
            estagio=estagio_lead,
            fonte=lead.fonte or 'Lead Migrado',
            descricao=lead.notas,
            data_criacao=lead.data_criacao
        )
        # Seta a data de criação retroativa via update para burlar o auto_now_add
        Oportunidade.objects.filter(id=opp.id).update(data_criacao=lead.data_criacao)
        
        # Vincular contato e empresa à oportunidade (M2M)
        opp.contatos.add(contato)
        if conta:
            opp.empresas.add(conta)
        
        # 3. Re-vincular itens relacionados
        # Diagnósticos
        DiagnosticoResultado.objects.filter(lead=lead).update(
            lead=None,
            conta=conta,
            oportunidade=opp
        )
        
        # Mensagens WhatsApp
        WhatsappMessage.objects.filter(lead=lead).update(
            lead=None,
            oportunidade=opp
        )
        
        # Histórico de Estágios
        HistoricoEstagio.objects.filter(lead=lead).update(
            lead=None,
            oportunidade=opp,
            tipo_objeto='OPORTUNIDADE'
        )
        
        # Atividades (Polimórficas)
        lead_ct = ContentType.objects.get_for_model(Lead)
        opp_ct = ContentType.objects.get_for_model(Oportunidade)
        Atividade.objects.filter(content_type=lead_ct, object_id=lead.id).update(
            content_type=opp_ct,
            object_id=opp.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_diagnosticoresultado_oportunidade_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_leads_para_oportunidades, migrations.RunPython.noop),
    ]
