# Generated by Django 4.2.7 on 2026-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037b_remove_lead_schema_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug para URLs públicas (ex: pernambuco)', max_length=100, null=True, unique=True),
        ),
    ]
