# Generated by Django 4.2.7 on 2026-01-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_lead_canal_remove_lead_estagio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='crm.conta'),
        ),
    ]
