# Generated by Django 4.2.7 on 2026-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_alter_contato_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
