# Generated by Django 4.2.7 on 2026-02-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_add_slug_to_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='estagio_inicial',
            field=models.ForeignKey(blank=True, help_text='Estágio inicial das novas oportunidades', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_estagio_inicial', to='crm.estagiofunil'),
        ),
        migrations.AddField(
            model_name='canal',
            name='funil_padrao',
            field=models.ForeignKey(blank=True, help_text='Funil para onde vão as novas oportunidades deste canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_funil_padrao', to='crm.funil'),
        ),
    ]
