# Generated by Django 4.2.7 on 2026-01-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_conta_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_adicionais', to='crm.conta')),
            ],
            options={
                'verbose_name': 'Marca Adicional',
                'verbose_name_plural': 'Marcas Adicionais',
                'ordering': ['nome'],
            },
        ),
    ]
