# Generated by Django 4.2.7 on 2026-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_add_funil_estagio_to_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funil',
            name='tipo',
            field=models.CharField(choices=[('VENDAS', 'Vendas'), ('POS_VENDA', 'Pós-Venda'), ('SUPORTE', 'Suporte')], default='VENDAS', max_length=20),
        ),
    ]
