# Generated by Django 4.2.7 on 2026-02-01 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_contamarca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='origem',
            field=models.ForeignKey(blank=True, help_text='Origem padronizada da oportunidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.origem'),
        ),
    ]
