# Generated by Django 4.2.7 on 2026-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_fix_funil_estagios'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='reacoes',
            field=models.JSONField(blank=True, default=list, help_text='Reações [{emoji, de_mim, numero}]'),
        ),
    ]
