# Generated by Django 4.2.7 on 2026-02-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_add_reacoes_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data_ativacao_cliente',
            field=models.DateTimeField(blank=True, help_text='Data em que a conta foi convertida para cliente ativo', null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='status_cliente',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('CLIENTE_ATIVO', 'Cliente Ativo'), ('INATIVO', 'Inativo')], default='PROSPECT', help_text='Status do cliente no ciclo comercial', max_length=20),
        ),
    ]
