# Generated by Django 4.2.7 on 2026-02-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_conta_data_ativacao_cliente_conta_status_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contas', to='crm.tag'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='oportunidades', to='crm.tag'),
        ),
    ]
