# Generated by Django 4.2.7 on 2026-03-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_add_tags_to_oportunidade_e_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado (UF) onde este canal atua (ex: PE, SP, RJ)', max_length=2, null=True),
        ),
    ]
