# Generated by Django 4.2.7 on 2026-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_add_estado_to_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='cor',
            field=models.CharField(default='#F97316', help_text='Cor hexadecimal do canal para exibição no mapa (ex: #F97316)', max_length=7),
        ),
    ]
