# Generated by Django 4.2.7 on 2026-03-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_add_cor_to_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número a bloquear (ex: 5581999999999)', max_length=50, unique=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo do bloqueio', max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número Bloqueado',
                'verbose_name_plural': 'Números Bloqueados',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
