# Generated by Django 5.2.12 on 2026-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_add_numero_bloqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do módulo (ex: Financeiro, Estoque, Vendas)', max_length=150)),
                ('descricao', models.TextField(blank=True, help_text='Conteúdo/escopo do módulo', null=True)),
                ('carga_horaria_estimada', models.PositiveIntegerField(default=60, help_text='Duração estimada em minutos')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na sequência padrão')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo de Treinamento',
                'verbose_name_plural': 'Módulos de Treinamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
