# Generated by Django 5.2.12 on 2026-03-16 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_add_modulo_treinamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='crm.conta')),
                ('oportunidade', models.ForeignKey(blank=True, help_text='Oportunidade que originou este onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings', to='crm.oportunidade')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Responsável pelo onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding de Cliente',
                'verbose_name_plural': 'Onboardings de Clientes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data', models.DateField(blank=True, help_text='Data do treinamento', null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('assinatura', models.TextField(blank=True, help_text='Assinatura digital em base64', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='crm.modulotreinamento')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='crm.onboardingcliente')),
                ('participantes', models.ManyToManyField(blank=True, help_text='Contatos da empresa que participaram', related_name='sessoes_treinamento', to='crm.contato')),
                ('treinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_como_treinador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Treinamento',
                'verbose_name_plural': 'Sessões de Treinamento',
                'ordering': ['onboarding', 'modulo__ordem'],
            },
        ),
    ]
