# Generated by Django 5.2.12 on 2026-03-16 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_add_onboarding_sessao_treinamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título/descrição do agendamento', max_length=200)),
                ('data', models.DateField(help_text='Data agendada')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('REAGENDADO', 'Reagendado')], default='AGENDADO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(blank=True, help_text='Módulo a ser treinado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='crm.modulotreinamento')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='crm.onboardingcliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_treinamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento de Treinamento',
                'verbose_name_plural': 'Agendamentos de Treinamento',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
